#!/bin/sh
set -eu

APP_DB_USER="${OED_DB_USER:-oed}"
APP_DB_PASSWORD="${OED_DB_PASSWORD:?OED_DB_PASSWORD is required for database initialization}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<EOF
DO \$\$
BEGIN
   IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${APP_DB_USER}') THEN
      CREATE ROLE ${APP_DB_USER} WITH LOGIN SUPERUSER PASSWORD '${APP_DB_PASSWORD}';
   ELSE
      ALTER ROLE ${APP_DB_USER} WITH LOGIN SUPERUSER PASSWORD '${APP_DB_PASSWORD}';
   END IF;
END
\$\$;

DROP DATABASE IF EXISTS oed;
CREATE DATABASE oed WITH OWNER ${APP_DB_USER};

DROP DATABASE IF EXISTS oed_testing;
CREATE DATABASE oed_testing WITH OWNER ${APP_DB_USER};

ALTER ROLE ${APP_DB_USER} SUPERUSER;
EOF
